package com.lct.www.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-02-20T14:52:48.157+08:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://service.www.lct.com/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://service.www.lct.com/", className = "com.lct.www.service.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://service.www.lct.com/", className = "com.lct.www.service.GetUserByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public User getUserById(
            @WebParam(name = "arg0", targetNamespace = "")
            Integer arg0
    );
}
